// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZTluiVV-Un5dS3Mm94lrdE28k5uvs87g',
    appId: '1:1052109071570:web:9f75138f10a7e8203cf90b',
    messagingSenderId: '1052109071570',
    projectId: 'blood-donation-364ab',
    authDomain: 'blood-donation-364ab.firebaseapp.com',
    storageBucket: 'blood-donation-364ab.appspot.com',
    measurementId: 'G-33TT6EXSMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJECL11sUTq5WauqvUwZcOwDa_YtL6M58',
    appId: '1:1052109071570:android:25b42e325a24f2f83cf90b',
    messagingSenderId: '1052109071570',
    projectId: 'blood-donation-364ab',
    storageBucket: 'blood-donation-364ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjaLtrsd_xC6EJ8JLe6wYZ1Ny-CVf9y3A',
    appId: '1:1052109071570:ios:21b4227644f2d2fb3cf90b',
    messagingSenderId: '1052109071570',
    projectId: 'blood-donation-364ab',
    storageBucket: 'blood-donation-364ab.appspot.com',
    iosBundleId: 'com.example.brgDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjaLtrsd_xC6EJ8JLe6wYZ1Ny-CVf9y3A',
    appId: '1:1052109071570:ios:21b4227644f2d2fb3cf90b',
    messagingSenderId: '1052109071570',
    projectId: 'blood-donation-364ab',
    storageBucket: 'blood-donation-364ab.appspot.com',
    iosBundleId: 'com.example.brgDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZTluiVV-Un5dS3Mm94lrdE28k5uvs87g',
    appId: '1:1052109071570:web:62265b9387aa5fae3cf90b',
    messagingSenderId: '1052109071570',
    projectId: 'blood-donation-364ab',
    authDomain: 'blood-donation-364ab.firebaseapp.com',
    storageBucket: 'blood-donation-364ab.appspot.com',
    measurementId: 'G-X0PGJQ4BV9',
  );
}
